#pragma once
void testListInsertAt();
void testListAppend();
void testListGetLength();
void testListGet();
void testListGetFirst();
void testListGetLast();
void testListGetOutOfRange();
void testListInsertAtOutOfRange();
void testListConcat();
void listSequenceWithUniquePtrTests();
